### ISSUE TITLE
存在很多空白页

### ISSUE THREAD

**Issue by nicai009** [chunkitlau/BeijingUniversityOfPostsAndTelecommunicationsMaster-PhdThesisTemplate#2]
您好，感谢您的项目，我在编译了项目初始文件后发现出现很多空白页，比如封面后，中文摘要后，英文摘要后，表格索引页后。这个问题在您参考的BUPTGraduateThesis-master项目中同样存在，有办法解决吗？

**Comment by chunkitlau** [comment]
这是这个项目的排版，主要目的是控制打印的时候内容从奇数页开始，具体来说封面、目录、每一章第一页应该是奇数页，以便翻阅的时候可以清楚看到。这个排版可以调整，具体可以修改项目代码，由于这个代码也是转载别人的，具体怎么修改可能需要自己研究。



 发自我的企业微信     
 
 &nbsp;


 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年3月15日(周二) 下午4:06写道:

  

 
您好，感谢您的项目，我在编译了项目初始文件后发现出现很多空白页，比如封面后，中文摘要后，英文摘要后，表格索引页后。这个问题在您参考的BUPTGraduateThesis-master项目中同样存在，有办法解决吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nicai009** [comment]
谢谢 我再研究一下
